### ISSUE TITLE
Responsiveness breaks for Timeline

### ISSUE THREAD

**Issue by everly-gif** [DevIncept/DevIncept.github.io#17]
I have noticed that the some elements break in mobile view.  

Sections:  

**Timeline**
**How it works section** (enhancement)

Im attaching some screenshots below
<br>
1. **Proposing to add some padding, margin and also fix content overflowing**  
<img src="https://user-images.githubusercontent.com/77877486/135562394-430c7b7d-6ab2-44de-a360-7759016ddbdf.jpeg" width=30% height=30%>  
<b>2. Proposing to change alignment - Icons on top and content below instead of side by side</b><br><br>  
<img src="https://user-images.githubusercontent.com/77877486/135562723-d32ede8c-a31a-4621-8836-356bfa3bc880.jpeg"width=30% height=30%>    

**If this is something you would like to implement, I would like to work on it myself, Therefore, asking you to assign me this issue, Thanks.**

**Comment by ashutoshkrris** [comment]
Sure @everly-gif 
Go on!

**Comment by everly-gif** [comment]
hey @ashutoshkrris  could I make the timeline one columned in smaller screens instead of double sided?
